libfsobasics: netlinkutils: work around a nasty bug in vala-0.14 with Posix.InAddr structure
We're using here our own InAddr structure as if we use the default one vala ships we get
the following compilation error:

netlinkutils.vala:58.35-58.48: error: `Posix.InAddr' does not have a default constructor
     Posix.InAddr inaddr = Posix.InAddr();

When this bug is fixed upstream we should use Posix.InAddr instead of
Posix.InAddr2 again.

Signed-off-by: Simon Busch <morphis@gravedo.de>