fsobasics: work around some bug? in vala-0.14 with sighandler_t delegate
When compiling with vala-0.14 we get the following error:

libinitexit.c: In function 'fso_framework_onSignal':
libinitexit.c:154:2: error: unknown type name 'sighandler_t'
libinitexit.c:212:10: warning: assignment makes integer from pointer without a cast [enabled by default]
libinitexit.c:213:2: warning: passing argument 2 of 'signal' makes pointer from integer without a cast [enabled by default]
/usr/include/signal.h:101:23: note: expected '__sighandler_t' but argument is of type 'int'

sighandler_t is definied in signal.h and is a GNU extension for libc which is only
available when _GNU_SOURCE is definied otherwise there is only sig_t available. This adds
the _GNU_SOURCE define as compiler flag.

Signed-off-by: Simon Busch <morphis@gravedo.de>